Repository wearerequired/traduttore, pull requests merged in 2020-03, with the labels that each got.

#171 Replace localheinz/composer-normalize with ergebnis/composer-normalize
  .travis.yml
Labels: [Component] Tests

#172 Fix typo in composer lint command
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Component] Docs, [Type] Bug

#170 Add filter to customize mapping of sources to translation entries.
  docs/hooks.md
  inc/Export.php
  tests/phpunit/tests/Export.php
Labels: [Type] Enhancement

#173 Use correct filter name in test_map_entries_to_source_filter()
  tests/phpunit/tests/Export.php
Labels: [Component] Tests, [Type] Bug
